name: installation
description: "Installation utility"
publish_to: 'none'
version: 0.1.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  file_picker: ^6.2.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  logger: ^2.1.0
  osc: ^1.0.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  process_run: ^0.14.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  system_tray: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
