name: installation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  file_picker: ^6.2.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  logger: ^2.1.0
  process_run: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
